### ISSUE TITLE
Unzip quotes

### ISSUE THREAD

**Issue by darthwalsh** [cyclelou/Amerpie#1]
👋 hi! came across https://www.reddit.com/r/ObsidianMD/comments/1dtuuwi/how_obsidian_cured_my_depression_saved_my_job_and/

A small suggestion: git normally isn't used to host binary files. If you add one new quote to [the zip file](https://github.com/cyclelou/Amerpie/blob/main/Quotes.zip), the git diff is not going to be meaningful.

(I also don't feel 100% comfortable unzipping a stranger's zip file; it's not the safest protocol.)

If you unzip it and upload text files to this repo, It would be more usable from the GitHub UI?

**Comment by cyclelou** [comment]
Hi Carl,

Done! My Git skills are very rudimentary, but ChatGPT helped me figure it out. I am still in the process of standardizing these notes, so you will find some to be in different layouts than others.

Lou in NC
https://louplummer.lol

From: Carl Walsh ***@***.***>
Date: Tuesday, September 17, 2024 at 11:14 AM
To: cyclelou/Amerpie ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [cyclelou/Amerpie] Unzip quotes (Issue #1)

👋 hi! came across https://www.reddit.com/r/ObsidianMD/comments/1dtuuwi/how_obsidian_cured_my_depression_saved_my_job_and/

A small suggestion: git normally isn't used to host binary files. If you add one new quote to the zip file<https://github.com/cyclelou/Amerpie/blob/main/Quotes.zip>, the git diff is not going to be meaningful.

(I also don't feel 100% comfortable unzipping a stranger's zip file; it's not the safest protocol.)

If you unzip it and upload text files to this repo, It would be more usable from the GitHub UI?

**Comment by darthwalsh** [comment]
Awesome, I see in f11f008d627ad3f2d2eccef2a41dab62983cb735 all the quotes. Thanks!
